src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image_url = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?int $fav = null;

    #[ORM\Column]
    private ?bool $status = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $categories = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?SecurityUser $users = null;

    /**
     * @var Collection<int, SecurityUser>
     */
    #[ORM\ManyToMany(targetEntity: SecurityUser::class, inversedBy: 'favorite')]
    private Collection $favorite;

    #[ORM\OneToOne(mappedBy: 'products', cascade: ['persist', 'remove'])]
    private ?Order $orders = null;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'products', orphanRemoval: true)]
    private Collection $messages;

    /**
     * @var Collection<int, Offer>
     */
    #[ORM\OneToMany(targetEntity: Offer::class, mappedBy: 'products', orphanRemoval: true)]
    private Collection $offers;

    /**
     * @var Collection<int, Notification>
     */
    #[ORM\OneToMany(targetEntity: Notification::class, mappedBy: 'product', orphanRemoval: true)]
    private Collection $notificationProduct;

    #[ORM\Column]
    private ?bool $holiday = null;

    public function __construct()
    {
        $this->favorite = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->offers = new ArrayCollection();
        $this->notificationProduct = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(string $image_url): static
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getFav(): ?int
    {
        return $this->fav;
    }

    public function setFav(int $fav): static
    {
        $this->fav = $fav;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCategories(): ?Category
    {
        return $this->categories;
    }

    public function setCategories(?Category $categories): static
    {
        $this->categories = $categories;

        return $this;
    }

    public function getUsers(): ?SecurityUser
    {
        return $this->users;
    }

    public function setUsers(?SecurityUser $users): static
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection<int, SecurityUser>
     */
    public function getFavorite(): Collection
    {
        return $this->favorite;
    }

    public function addFavorite(SecurityUser $favorite): static
    {
        if (!$this->favorite->contains($favorite)) {
            $this->favorite->add($favorite);
        }

        return $this;
    }

    public function removeFavorite(SecurityUser $favorite): static
    {
        $this->favorite->removeElement($favorite);

        return $this;
    }

    public function getOrders(): ?Order
    {
        return $this->orders;
    }

    public function setOrders(Order $orders): static
    {
        // set the owning side of the relation if necessary
        if ($orders->getProducts() !== $this) {
            $orders->setProducts($this);
        }

        $this->orders = $orders;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setProducts($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getProducts() === $this) {
                $message->setProducts(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Offer>
     */
    public function getOffers(): Collection
    {
        return $this->offers;
    }

    public function addOffer(Offer $offer): static
    {
        if (!$this->offers->contains($offer)) {
            $this->offers->add($offer);
            $offer->setProducts($this);
        }

        return $this;
    }

    public function removeOffer(Offer $offer): static
    {
        if ($this->offers->removeElement($offer)) {
            if ($offer->getProducts() === $this) {
                $offer->setProducts(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotificationProduct(): Collection
    {
        return $this->notificationProduct;
    }

    public function addNotificationProduct(Notification $notificationProduct): static
    {
        if (!$this->notificationProduct->contains($notificationProduct)) {
            $this->notificationProduct->add($notificationProduct);
            $notificationProduct->setProduct($this);
        }

        return $this;
    }

    public function removeNotificationProduct(Notification $notificationProduct): static
    {
        if ($this->notificationProduct->removeElement($notificationProduct)) {
            // set the owning side to null (unless already changed)
            if ($notificationProduct->getProduct() === $this) {
                $notificationProduct->setProduct(null);
            }
        }

        return $this;
    }

    public function isHoliday(): ?bool
    {
        return $this->holiday;
    }

    public function setHoliday(bool $holiday): static
    {
        $this->holiday = $holiday;

        return $this;
    }
}

src/Controller/ProductBuyerController.php
<?php

namespace App\Controller;

use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use App\Service\FavoriteService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;

class ProductBuyerController extends AbstractController
{
    #[Route('/', name: 'app_product_buyer')]
    public function index(Request $request, ProductRepository $productRepository, FavoriteService $favoriteService, CategoryRepository $categoryRepository): Response
    {

        //////////////////security////////////////////
        if($this->getUser() === null){
            return $this->redirectToRoute('app_login');
        }
        //////////////////////////////////////////////

        $productList = $productRepository->findAll();
        $categoryList = $categoryRepository->findAll();
        $updatedProductList = [];
        $bMe = false;
        $catalogUser = false;

        foreach ($productList as $product) {
            $favoriteService->updateFav($product);
            if($product->getUsers() !== $this->getUser()) {
                $updatedProductList[] = $product;
            }
        }

        return $this->render('catalog/index.html.twig', [
            'controller_name' => 'ProductBuyerController',
            'productList' => $updatedProductList,
            'categoryList' => $categoryList,
            'bMe' => $bMe,
            'catalogUser' => $catalogUser,
            'user' => $this->getUser(),
        ]);
    }

}

templates/product_buyer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductBuyerController!{% endblock %}
{% block body %}
    <style>
        body {
            background: #414852;
            font-family: 'Montserrat', sans-serif;
            margin: 0;
            padding: 0;
        }
        .wrapper {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            grid-auto-flow: dense;
            grid-gap: 20px;
            margin: 6% auto 0;
            width: 90%;
        }

        .single-card {
            position: relative;
            max-width: 100%;
            margin: 0;
            box-shadow: 0 2px 20px rgba(0, 0, 0, 0.5);
            transition: box-shadow 0.3s ease;
            overflow: hidden;
            background: #414852;
            border-radius: 15px;
            transition: all 0.2s ease-in-out;
            display: flex;
            flex-direction: column;
        }

        .single-card:hover {
            transform: scale(1.05);
        }

        .img-area {
            position: relative;
            width: 100%;
            height: 250px;
            overflow: hidden;
        }

        .img-area img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            transition: transform 0.3s ease;
        }

        .img-area:hover img {
            transform: scale(1.1);
        }

        .overlay {
            position: absolute;
            top: 0;
            left: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            width: 100%;
            height: 100%;
            background-color: rgba(150, 150, 150, 0.4);
            opacity: 0;
            transition: opacity 0.3s ease;
        }

        .single-card:hover .overlay {
            opacity: 1;
        }

        .add-to-fav, .remove-from-fav, .make-offer {
            padding: 10px 15px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 1px;
            cursor: pointer;
            transition: background-color 0.3s ease, color 0.3s ease;
            margin-bottom: 10px;
        }

        .add-to-fav:hover, .remove-from-fav:hover, .make-offer:hover {
            color: #ff0000;
        }

        .price {
            font-weight: bold;
            font-size: larger;
        }

        .info {
            display: flex;
            flex-direction: column;
            padding: 10px;
            color: #ddd;
            line-height: 25px;
        }

        .row1 {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

    </style>
    <div class="wrapper">
        {% for product in productList %}
            {% if product.status %}
                <div class="single-card">
                    <div class="img-area">
                        <img src="{{ product.imageUrl }}" alt="">
                        <div class="overlay">
                                <button class="remove-from-fav" data-id="{{ product.id }}" {% if not FavoriteService.checkFav(product.id) %} style="display: none;" {% endif %}><svg xmlns="http://www.w3.org/2000/svg" height="25" width="25" viewBox="0 0 512 512"><path fill="#ff0000" d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z"/></svg></button>
                                <button class="add-to-fav" data-id="{{ product.id }}" {% if FavoriteService.checkFav(product.id) %} style="display: none;" {% endif %} ><svg xmlns="http://www.w3.org/2000/svg" height="25" width="25" viewBox="0 0 512 512"><path fill="#000000" d="M225.8 468.2l-2.5-2.3L48.1 303.2C17.4 274.7 0 234.7 0 192.8l0-3.3c0-70.4 50-130.8 119.2-144C158.6 37.9 198.9 47 231 69.6c9 6.4 17.4 13.8 25 22.3c4.2-4.8 8.7-9.2 13.5-13.3c3.7-3.2 7.5-6.2 11.5-9c0 0 0 0 0 0C313.1 47 353.4 37.9 392.8 45.4C462 58.6 512 119.1 512 189.5l0 3.3c0 41.9-17.4 81.9-48.1 110.4L288.7 465.9l-2.5 2.3c-8.2 7.6-19 11.9-30.2 11.9s-22-4.2-30.2-11.9zM239.1 145c-.4-.3-.7-.7-1-1.1l-17.8-20-.1-.1s0 0 0 0c-23.1-25.9-58-37.7-92-31.2C81.6 101.5 48 142.1 48 189.5l0 3.3c0 28.5 11.9 55.8 32.8 75.2L256 430.7 431.2 268c20.9-19.4 32.8-46.7 32.8-75.2l0-3.3c0-47.3-33.6-88-80.1-96.9c-34-6.5-69 5.4-92 31.2c0 0 0 0-.1 .1s0 0-.1 .1l-17.8 20c-.3 .4-.7 .7-1 1.1c-4.5 4.5-10.6 7-16.9 7s-12.4-2.5-16.9-7z"/></svg></button>

                            <button class="make-offer">Make an offer</button>
                        </div>
                    </div>
                    <div class="info">
                        <div class="row1">
                            <span class="price">{{ product.price }} €</span>
                            <span>❤️{{ product.fav }}</span>
                        </div>
                        <span class="category">{{ product.title }}</span>
                        <span>{{ product.description }}</span>
                        <span>vendu par {{ product.users.username }}</span>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <script>
        document.querySelectorAll('.add-to-fav').forEach(button => {
            button.addEventListener('click', function () {
                const productId = this.getAttribute('data-id');

                fetch(`/add-favorite/${productId}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    body: JSON.stringify({ productId: productId })
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            // Update button visibility
                            this.style.display = 'none'; // Hide add button
                            this.closest('.overlay').querySelector('.remove-from-fav').style.display = 'block'; // Show remove button
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                    });
            });
        });

        document.querySelectorAll('.remove-from-fav').forEach(button => {
            button.addEventListener('click', function () {
                const productId = this.getAttribute('data-id');

                fetch(`/remove-favorite/${productId}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    body: JSON.stringify({ productId: productId })
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            // Update button visibility
                            this.style.display = 'none'; // Hide remove button
                            this.closest('.overlay').querySelector('.add-to-fav').style.display = 'block'; // Show add button
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                    });
            });
        });
    </script>
{% endblock %}